var selectors=[
"html,body,head,title",
"#title",
"h1#title",
"[id=title]",
"[name=asdf]",
"div",
"div p",
"div p a",
"div > p",
"p > a",
"div > p > a",
"div + p",
"div ~ p",
"p ~ div",
"dl > dt ~ dd",
".note",
"div.example",
"div[class=example]",
"div[class^=exa][class$=mple]",
"div[class^=exa]",
"div[class$=mple]",
"div[class*=e]",
"div[class|=dialog]",
"div[class~=example]",
"div ~ p:nth-child(even)",
"h1#title + div > p",
"div.subtoc + h2 > a",
"div, p, a",
"div.example, div.note",
"div:not(.example)",
"td *[type=submit]",
"div > input,div > select,div > button,div > textarea,div > button",
"table.selectorsReview td:not(:empty)",
"a:nth-child(2n)",
"a:nth-child(2n+1)",
"a:nth-child(odd)",
"a:nth-child(even)",
"div p:nth-child(odd) > a:nth-child(even)",
"p:nth-child(even) > a:nth-child(odd)",
"a:nth-child(n)",
"a:only-child",
"a:last-child",
"a:first-child",
"ul .tocline2",
"ul.toc li.tocline2",
"div[class]",
"ul.toc > li.tocline2",
"a:nth-child(odd)[name]",
"[class^=toc] a",
"ul li",
"[class] #title",
"body table tr>td a[href^='#']",
".subtoc li[class^=tocline]",
".subtoc li[class^=tocline] a",
"div :has(li a)",
"a:not(li a)",
"a:not(li a:nth-child(2n+1)):nth-child(3n)",
"a:odd",
"a:even",
"a:nth(3)",
"a:eq(155)",
"a:lt(10)",
"a:gt(100)",
"a:first",
"a:last",
"p:odd,a:even"
];